# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('post_date', models.DateField(verbose_name='date published')),
                ('image_name', models.CharField(max_length=50)),
                ('sale', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=4)),
                ('temporary_price', models.CharField(max_length=4)),
            ],
        ),
    ]
