# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
