# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170130_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
