# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170209_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
