# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170209_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='product_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
